configurable project root path
closes #1

diff --git a/.github/actions/get-export-name/action.yml b/.github/actions/get-export-name/action.yml
--- a/.github/actions/get-export-name/action.yml
+++ b/.github/actions/get-export-name/action.yml
@@ -17,7 +17,11 @@ runs:
     - name: Get export name
       id: get-export-name
       run: |
+        cd "${{ env.PROJECT_PATH }}"
         wget -nv 'https://raw.githubusercontent.com/bend-n/godot-actions/main/.github/actions/get-export-name/get-export-name.py' -O get-export-name.py
-        python get-export-name.py "${{ inputs.platform }}" || echo "::notice file=export_presets.cfg,title=Missing Configuration::No export for ${{ inputs.platform }}."
+        python get-export-name.py "${{ inputs.platform }}" || (
+          echo "::error file=${PROJECT_PATH}/export_presets.cfg,title=Missing Configuration::No export for ${{ inputs.platform }}."
+          exit 1
+        )
         echo "::set-output name=export-name::$(python get-export-name.py "${{ inputs.platform }}")"
       shell: bash
